### PR TITLE
Add password hash

### PR DESCRIPTION
**Pull request by maomihz**

### CODE REVIEW

**Comment by maomihz** [comment]
The form validator is independent from storage in database. The validator checks for the real password without hashing, so length of 80 should be fine. The password is only hashed after form validation, before storing in the database.

**Comment by maomihz** [comment]
I have also added hash for security answers and a function to check security answers. I have changed user_manager.py so that the code is more clear and follow PEP8.

**Comment by maomihz** [comment]
Please let me know if there is any other parts I can help!

**Review by unkown512 — CHANGES_REQUESTED** [review]
I agree with the 80 char for the form validation.

1) add_user change: For user_add function we want it to stay at just db and user_data but change the user_data to a dictionary so that if the table grows it is easier to modify. It is currently a list and should be accessed as user_data['phone'] and etc... For example we will add the field last_login and possibly more.

2) Keep tabs to two spaces. If you use vi the following command will work (This is due to html/js being 2 spaces and not having to swap back and forth without making mistakes):

:set tabstop=2 shiftwidth=2 expandtab
:retab

3) Do not change {} to dict -- see quote. "With CPython 2.7, using dict() to create dictionaries takes up to 6 times longer and involves more memory allocation operations than the literal syntax. Use {} to create dictionaries, especially if you are pre-populating them, unless the literal syntax does not work for your case."

After the password hash you can work on adding a salt to it and generating a unique_key (defined in user manager) for each user/session.

**Comment by maomihz** [comment]
Thanks for all your suggestions! I have modified the code to follow the team convention. Sorry for the confusion for changing function parameters.

I'm not sure if I understand the use case for unique_key. What should I do to that function?

The password hash stored is pbkdf2 `pbkdf2:sha256:150000$6klRlWp6$52bcc481636bdfcd3e45cc082cd0f469d1e54fdcd07640b30340028dc5cf63c9`, it already combines hashing, salting (`6klRlWp6`), and multiple iterations (`150000` times). The salt is random, so the salt is good enough for now.

**Comment by unkown512** [comment]
The unique key function sets a secret key for the flask application to encrypt cookies and etc. We can also use this to confirm form submissions and etc. 

I read the library you used for the encryption and looks good!

Thank you for these changes!

**Review by unkown512 — APPROVED** [review]

**Pull request merged**
