### PR TITLE
Fix not storing hash in database

### PR DESCRIPTION
**Pull request by maomihz**
Fix the problem mentioned in #9. I missed that when fixing the format, glad you tested it out!

### CODE REVIEW

**Review by unkown512 — APPROVED** [review]

**Comment by unkown512** [comment]
We should also hash the emails and phone numbers. Could you work on this?

**Comment by unkown512** [comment]
Also go ahead and add the same encryption to the Database setup file (admin#1510 user). There are some weird errors in this when it runs, so that would be good to look at.

**Comment by maomihz** [comment]
If we hash emails and phone numbers, then they are not retrievable anymore. Is it what we need?

**Comment by unkown512** [comment]
Ah you are right never mind on this

**Comment by unkown512** [comment]
Just tested the pwhash and works great! Just create a secret key (unique key function) that is pretty secure.

**Comment by maomihz** [comment]
Should the secret key function return a random string each time it gets called, or should we use a fixed random string?

**Comment by unkown512** [comment]
Needs to be random each time it is called

**Pull request merged**
